ifndef NAME
$(error "You can not run this Makefile without having NAME defined")
endif

CURL	?= $(shell if test -f /usr/bin/curl ; then echo "curl -H Pragma: -O -R -S --fail --show-error" ; fi)
WGET	?= $(shell if test -f /usr/bin/wget ; then echo "wget -nd -m" ; fi)
CLIENT	?= $(if $(CURL),$(CURL),$(if $(WGET),$(WGET)))

LOOKASIDE_HOST := http://pkgs.gooselinux.org
LOOKASIDE_URI := $(LOOKASIDE_HOST)/pkgs

